name: Lint

on: [push, pull_request]

env:
  APP_ENV: testing

jobs:
  lint:
    name: Lint all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - name: Install Composer dependencies
        run: >-
          composer config -g github-oauth.github.com 98cbc568911ef1e060a3a31623f2c80c1786d5ff
          && composer install --prefer-dist --no-progress

      - name: Install js dependencies
        run: yarn --frozen-lockfile

      - run: yarn lint
      - run: ./bin/update_licence.sh -nf

      - name: PHP_CodeSniffer check
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
